version: "3.8"
services:
  app:
    build: .
    container_name: fastapi-tic-tac-toe
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000

